export const posts = [
  {
    date: '2021-12-31',
    dailyPosts: [
      {
        id: '31-a',
        slug: '2021-12-31-a',
        type: 'blog',
        duration: '',
        title: 'Disable button after a click in angular using directive',
        url: 'https://singh-prateek.medium.com/disable-button-after-a-click-in-angular-using-directive-e3ff065683b8',
        description:
          'Background: need of directive to disable a button\n\nWe have a use case where the user has requested for the button to be disabled immediately after the click.\nThe first option is to set the disabled property of a button. But this feature we have to do for all buttons and a few places we have observables and validations. Considering all cases we have decided to use a directive.',
        imgUrl: '2021-12-31-a.jpg',
        datePosted: '2021-12-31',
        dateSource: '2021-12-31',
        postedBy: 'Steve Witman',
        sourceSite: 'Medium',
        sourceUrl: 'https://medium.com/tag/angular/latest',
        authorName: 'Prateek Singh',
        authorUrl: 'https://singh-prateek.medium.com',
        speakers: ['Prateek Singh'],
        tags: ['Directives'],
      },
      {
        id: '31-b',
        slug: '2021-12-31-b',
        type: 'blog',
        duration: '',
        title:
          'How to read, create/update and remove, listen on/off from the Firebase database in Web(Angular)?',
        url: 'https://imvikaskohli.medium.com/how-to-read-create-update-and-remove-listen-on-off-from-the-firebase-database-in-web-angular-238ba45c88a5',
        description:
          'In the firebase database, sometimes we need to only read value. But for the admin panel, we need to read, write and delete values in the database',
        imgUrl: '2021-12-31-b.jpg',
        datePosted: '2021-12-31',
        dateSource: '2021-12-31',
        postedBy: 'Steve Witman',
        sourceSite: 'Medium',
        sourceUrl: 'https://medium.com/tag/angular/latest',
        authorName: 'Vikas Kohli',
        authorUrl: 'https://imvikaskohli.medium.com',
        speakers: ['Vikas Kohli'],
        tags: ['Firebase'],
      },
      {
        id: '31-c',
        slug: '2021-12-31-c',
        type: 'video',
        duration: '5',
        title: 'Angular Material #25 - Progress Bar Component',
        url: 'https://www.youtube.com/watch?v=Jp3CYgL5E5M',
        description:
          'Angular Material is a UI Component-Based Library for Angular and through this series, we will take a look into each feature that Angular Material has to offer.',
        imgUrl: '2021-12-31-c.jpg',
        datePosted: '2021-12-31',
        dateSource: '2021-12-31',
        postedBy: 'Steve Witman',
        sourceSite: 'YouTube',
        sourceUrl: 'https://youtube.com',
        authorName: 'Omerko',
        authorUrl: 'https://www.youtube.com/c/Omerko/videos',
        speakers: [],
        tags: ['Angular Material'],
      },
      {
        id: '31-d',
        slug: '2021-12-31-d',
        type: 'blog',
        duration: '',
        title: 'How to display app version from package.json file in Angular',
        url: 'https://dev.to/aakashgoplani/how-to-display-app-version-from-packagejson-file-in-angular-137p',
        description:
          "I had this requirement to display or keep track of application version that we are currently using in our environments. Typically any mid to large scale organization have multiple dedicated environments where we deploy our application. There is chance that different version could have been deployed in one environment then other. Arguably, this isn't any problem, but only way to know which version is deployed to what environment is to check it on the console / dashboard of the deployment tool (like uDeploy or similar...) that we are using!",
        imgUrl: '2021-12-31-d.jpg',
        datePosted: '2021-12-31',
        dateSource: '2021-12-31',
        postedBy: 'Steve Witman',
        sourceSite: 'DEV Community',
        sourceUrl:
          'https://dev.to/search?q=angular&sort_by=published_at&sort_direction=desc',
        authorName: 'Aakash Goplani',
        authorUrl: 'https://dev.to/aakashgoplani',
        speakers: ['Aakash Goplani'],
        tags: [],
      },
      {
        id: '31-e',
        slug: '2021-12-31-e',
        type: 'blog',
        duration: '',
        title: 'Disabling browser back navigation in Angular',
        url: 'https://dev.to/aakashgoplani/disabling-browser-back-navigation-in-angular-2hd6',
        description:
          'To prevent browse back navigation we make use of History.pushState()web api. As soon as the user lands on the component where we want to disable back navigation, we set ...',
        imgUrl: '2021-12-31-e.jpg',
        datePosted: '2021-12-31',
        dateSource: '2021-12-31',
        postedBy: 'Steve Witman',
        sourceSite: 'DEV Community',
        sourceUrl:
          'https://dev.to/search?q=angular&sort_by=published_at&sort_direction=desc',
        authorName: 'Aakash Goplani',
        authorUrl: 'https://dev.to/aakashgoplani',
        speakers: ['Aakash Goplani'],
        tags: [],
      },
      {
        id: '31-f',
        slug: '2021-12-31-f',
        type: 'blog',
        duration: '',
        title: 'Angular Template form control in separate reusable component',
        url: 'https://dev.to/gaurangdhorda/angular-template-form-control-in-separate-reusable-component-1c9h',
        description:
          'This article is all about angular Template driven forms in angular. But When working with angular forms we have two approach to select: 1. Template Driven Form, 2. Reactive Forms',
        imgUrl: '2021-12-31-f.jpg',
        datePosted: '2021-12-31',
        dateSource: '2021-12-31',
        postedBy: 'Steve Witman',
        sourceSite: 'DEV Community',
        sourceUrl:
          'https://dev.to/search?q=angular&sort_by=published_at&sort_direction=desc',
        authorName: 'GaurangDhorda',
        authorUrl: 'https://dev.to/aakashgoplani',
        speakers: ['Gaurang Dhorda'],
        tags: [],
      },
      {
        id: '31-g',
        slug: '2021-12-31-g',
        type: 'blog',
        duration: '',
        title: 'Creating Custom Directives in Angular',
        url: 'https://dev.to/this-is-angular/custom-directives-in-angular-2cp5',
        description:
          'Today we will learn how to create our own directives in Angular. In my previous posts I discussed all the built-in directives which Angular provided. If you are unaware, I would highly suggest you to start from the part_1 (of the 6 series post).',
        imgUrl: '2021-12-31-g.jpg',
        datePosted: '2021-12-31',
        dateSource: '2021-12-31',
        postedBy: 'Steve Witman',
        sourceSite: 'DEV Community',
        sourceUrl:
          'https://dev.to/search?q=angular&sort_by=published_at&sort_direction=desc',
        authorName: 'Anubhab Mukherjee',
        authorUrl: 'https://dev.to/anubhab5',
        speakers: ['Anubhab Mukherjee'],
        tags: ['Custom Directives'],
      },
      {
        id: '31-h',
        slug: '2021-12-31-h',
        type: 'blog',
        duration: '',
        title: 'Dynamically import module in Angular',
        url: 'https://dev.to/railsstudent/dynamically-import-module-in-angular-29n6',
        description:
          'The elements of Spanish menu application https://github.com/railsstudent/ng-spanish-menu are primarily texts and buttons, and the user interface looks plain on first glance. I want to make it interesting by rendering an icon when quantity is below threshold.',
        imgUrl: '2021-12-31-h.jpg',
        datePosted: '2021-12-31',
        dateSource: '2021-12-31',
        postedBy: 'Steve Witman',
        sourceSite: 'DEV Community',
        sourceUrl:
          'https://dev.to/search?q=angular&sort_by=published_at&sort_direction=desc',
        authorName: 'Connie Leung',
        authorUrl: 'https://dev.to/railsstudent',
        speakers: ['Connie Leung'],
        tags: ['Modules'],
      },
    ],
  },
  {
    date: '2022-01-01',
    dailyPosts: [
      {
        id: '01-a',
        slug: '2022-01-01-a',
        type: 'video',
        duration: '11',
        title:
          'Angular Unit testing- 24 | Unit testing Form Control valueChanges Property Reactive Forms | Part 6',
        url: 'https://www.youtube.com/watch?v=RGNdT3vb4kM',
        description:
          'In this video, you will learn How to test angular valueChanges property of form control in reactive forms.',
        imgUrl: '2022-01-01-a.jpg',
        datePosted: '2022-01-01',
        dateSource: '2022-01-01',
        postedBy: 'Steve Witman',
        sourceSite: 'YouTube',
        sourceUrl: 'https://youtube.com',
        authorName: 'TechshareSKK',
        authorUrl:
          'https://www.youtube.com/channel/UCD8gC85u512FeCFzRV4Ll-A/videos',
        speakers: ['Sai Kumar Korthivada'],
        tags: ['Testing', 'Forms', 'Reactive Forms', 'valueChanges'],
      },
      {
        id: '01-b',
        slug: '2022-01-01-b',
        type: 'video',
        duration: '36',
        title: 'Angular Beginner to Advanced | Day 5 | WebAppUpgrade',
        url: 'https://www.youtube.com/watch?v=yXfAU3dGvaU',
        description:
          'In five days take your Angular skills to the next level, from beginners to Advanced.',
        imgUrl: '2022-01-01-b.jpg',
        datePosted: '2022-01-01',
        dateSource: '2021-12-31',
        postedBy: 'Steve Witman',
        sourceSite: 'YouTube',
        sourceUrl: 'https://youtube.com',
        authorName: 'The Web Dev',
        authorUrl:
          'https://www.youtube.com/channel/UCRf7mazcufqZxd2pR3oQJuQ/videos',
        speakers: ['Nabendu Biswas'],
        tags: [],
      },
      {
        id: '01-c',
        slug: '2022-01-01-c',
        type: 'blog',
        duration: '',
        title: 'Creating custom pagination component with Angular',
        url: 'https://medium.com/@kirill.kovzel/creating-custom-pagination-component-with-angular-9c6c93fdf0f0',
        description:
          "Pagination is undoubtedly one of the most popular approaches to dozed content representation. And it's absolutely fine to use some out-of-the-box solutions for it if your application uses some library like NgBootstrap or Material UI all round and the designs and functionality they provide is satisfactory to you.\n\nBut once you bump into the need of re-styling or customisation of it you usually may choose the way of creating a wrapping component which uses this out-of-the-box component inside and re-define its behaviour or styles by breaking original component encapsulation.",
        imgUrl: '2022-01-01-c.jpg',
        datePosted: '2022-01-01',
        dateSource: '2022-01-01',
        postedBy: 'Steve Witman',
        sourceSite: 'DEV Community',
        sourceUrl:
          'https://dev.to/search?q=angular&sort_by=published_at&sort_direction=desc',
        authorName: 'Kirill Kovzel',
        authorUrl: 'https://medium.com/@kirill.kovzel',
        speakers: ['Kirill Kovzel'],
        tags: ['Pagination'],
      },
      {
        id: '01-d',
        slug: '2022-01-01-d',
        type: 'video',
        duration: '9',
        title: 'HTTP Interceptor in angular',
        url: 'https://www.youtube.com/watch?v=bMyP7WVmzbU',
        description: '',
        imgUrl: '2022-01-01-d.jpg',
        datePosted: '2022-01-01',
        dateSource: '2022-01-01',
        postedBy: 'Steve Witman',
        sourceSite: 'YouTube',
        sourceUrl: 'https://youtube.com',
        authorName: 'Vikas',
        authorUrl: 'https://www.youtube.com/c/RealAppsniksviks/videos',
        speakers: ['Vikas'],
        tags: ['HTTP Inteceptors'],
      },
      {
        id: '01-e',
        slug: '2022-01-01-e',
        type: 'video',
        duration: '21',
        title:
          'LocalStorage, sessionStorage in ANGULAR | Local Storage with example.',
        url: 'https://www.youtube.com/watch?v=HznHppdgBpA',
        description:
          'Creating a angular application. Create a component with a form if needed.  Create a click event to call and store data in localstorage and set the data.',
        imgUrl: '2022-01-01-e.jpg',
        datePosted: '2022-01-01',
        dateSource: '2021-01-01',
        postedBy: 'Steve Witman',
        sourceSite: 'YouTube',
        sourceUrl: 'https://youtube.com',
        authorName: 'coding wall',
        authorUrl:
          'https://www.youtube.com/channel/UCxjJshhu0QBbztNZei4udOA/videos',
        speakers: [],
        tags: ['localStorage', 'sessionStorage'],
      },
      {
        id: '01-f',
        slug: '2022-01-01-f',
        type: 'blog',
        duration: '',
        title: 'View Encapsulation in Angular',
        url: 'https://makesh-kumar.medium.com/view-encapsulation-in-angular-fbebf7467072',
        description:
          'Encapsulation is one of the fundamental concepts in object-oriented programming (OOP). It defines the idea that all the data and methods that operate on that data are kept private or encapsulated in a single unit. It is like hiding the implementation detail from the outside world. The consumer of encapsulated object know that it works, but do not know how it works.',
        imgUrl: '2022-01-01-f.jpg',
        datePosted: '2022-01-01',
        dateSource: '2022-01-01',
        postedBy: 'Steve Witman',
        sourceSite: 'Medium',
        sourceUrl: 'https://medium.com/tag/angular/latest',
        authorName: 'Makesh Kumar',
        authorUrl: 'https://makesh-kumar.medium.com',
        speakers: ['Makesh Kumar'],
        tags: ['ViewEncapsulation'],
      },
      {
        id: '01-g',
        slug: '2022-01-01-g',
        type: 'blog',
        duration: '',
        title: 'Custom Angular reactive form with SVG and clickable elements',
        url: 'https://dev.to/hanneslim/how-to-build-a-custom-angular-reactive-svg-form-with-clickable-elements-1a5k',
        description:
          'During the Corona pandemic, many companies and employees discovered home office. As a result, it became apparent that not every employee required his own workstation. Instead, companies now offer a shared desk model. This means that employees flexibly share workstations. Often, you can reserve your desired workstation in advance. This workplace booking function has attracted me for some time. I find the possibility to create a Custom Reactive Form in Angular, which also includes an office plan, particularly interesting. In the Custom Angular Reactive SVG Form there is the possibility to select a workstation from the office plan and to mark it with a color. As soon as a workstation has been chosen, the form will be validated and the desk will be bookable. In the following the implementation is explained step by step.',
        imgUrl: '2022-01-01-g.jpg',
        datePosted: '2022-01-01',
        dateSource: '2022-01-01',
        postedBy: 'Steve Witman',
        sourceSite: 'DEV Community',
        sourceUrl:
          'https://dev.to/search?q=angular&sort_by=published_at&sort_direction=desc',
        authorName: 'hanneslim',
        authorUrl: 'https://dev.to/hanneslim',
        speakers: [],
        tags: ['Forms', 'Reactive Forms'],
      },
    ],
  },
  {
    date: '2022-01-02',
    dailyPosts: [
      {
        id: '02-a',
        slug: '2022-01-02-a',
        type: 'blog',
        duration: '',
        title: 'Built-In Angular Pipes - Part 1',
        url: 'https://dev.to/this-is-angular/built-in-angular-pipes-part-1-23ec',
        description:
          'Today we will be learning on a very important concept provided by Angular - Pipes. The main use of Pipe is to transform the appearance of the data before showing to the user. ',
        imgUrl: '2022-01-02-a.jpg',
        datePosted: '2022-01-02',
        dateSource: '2022-01-02',
        postedBy: 'Steve Witman',
        sourceSite: 'DEV Community',
        sourceUrl:
          'https://dev.to/search?q=angular&sort_by=published_at&sort_direction=desc',
        authorName: 'Anubhab Mukherjee',
        authorUrl: 'https://dev.to/anubhab5',
        speakers: ['Anubhab Mukherjee'],
        tags: ['Pipes'],
      },
      {
        id: '02-b',
        slug: '2022-01-02-b',
        type: 'video',
        duration: '13',
        title:
          'Angular 13 new features | Micro Front End is coming | Angular 14 updates',
        url: 'https://www.youtube.com/watch?v=FgItZM4yHvY',
        description:
          "Angular 13 has been released. Let’s have a look at the new in this Angular 13 tutorial. we'll learn what's the new feature of the angular 13 version. We will also talk about the Angular 14 updates and big news about the Micro Font End in the Angular framework.",
        imgUrl: '2022-01-02-b.jpg',
        datePosted: '2022-01-02',
        dateSource: '2021-01-01',
        postedBy: 'Steve Witman',
        sourceSite: 'YouTube',
        sourceUrl: 'https://youtube.com',
        authorName: 'codeWithAmi',
        authorUrl: 'https://www.youtube.com/c/codeWithAmi/videos',
        speakers: [],
        tags: [],
      },
      {
        id: '02-c',
        slug: '2022-01-02-c',
        type: 'blog',
        duration: '',
        title:
          'Firebase Authentication - Getting started with Firebase Authentication using Angular code example',
        url: 'https://medium.com/@liatkomp/firebase-authentication-f0445ac732cb',
        description:
          "Website application development brings us many challenges. One of them is users' identity. Using Firebase Authentication makes this mission simpler, saves us a significant amount of time, and speeds up code implementation. This post will cover Firebase Authentication — how, when, and why to use Firebase Authentication.",
        imgUrl: '2022-01-02-c.jpg',
        datePosted: '2022-01-02',
        dateSource: '2022-01-01',
        postedBy: 'Steve Witman',
        sourceSite: 'Medium',
        sourceUrl: 'https://medium.com/tag/angular/latest',
        authorName: 'Liat Kompas',
        authorUrl: 'https://medium.com/@liatkomp',
        speakers: ['Liat Kompas'],
        tags: ['Firebase', 'Auth'],
      },
    ],
  },
];
